/********************************************************************
Vireio Perception : Open-Source Stereoscopic 3D Driver
Copyright (C) 2012 Andres Hernandez

Aquilinus : Vireio Perception 3D Modification Studio 
Copyright © 2014 Denis Reischl

Vireio Perception Version History:
v1.0.0 2012 by Andres Hernandez
v1.0.X 2013 by John Hicks, Neil Schneider
v1.1.x 2013 by Primary Coding Author: Chris Drain
Team Support: John Hicks, Phil Larkson, Neil Schneider
v2.0.x 2013 by Denis Reischl, Neil Schneider, Joshua Brown
v2.0.4 to v3.0.x 2014-2015 by Grant Bagwell, Simon Brown and Neil Schneider
v4.0.x 2015 by Denis Reischl, Grant Bagwell, Simon Brown and Neil Schneider

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
********************************************************************/
#ifndef NOD_ID3D11DEVICECONTEXT
#define NOD_ID3D11DEVICECONTEXT

#include"VMT_ID3D11DeviceContext.h"

#pragma region IUnknown methods
/**
* HRESULT WINAPI QueryInterface
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_QueryInterface, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::QueryInterface");
AQU_D3D_NODE_COMMANDER(AQU_REFIID, L"riid");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_VOID, L"ppvObject");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_IUNKNOWN::QueryInterface);
AQU_D3D_NODE_FOOTER___;

/**
* ULONG WINAPI AddRef
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_AddRef, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::AddRef");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_IUNKNOWN::AddRef);
AQU_D3D_NODE_FOOTER___;

/**
* ULONG WINAPI Release
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_Release, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::Release");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_IUNKNOWN::Release);
AQU_D3D_NODE_FOOTER___;

#pragma endregion

#pragma region ID3D11DeviceChild methods
/**
* void WINAPI GetDevice
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_GetDevice, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::GetDevice");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11DEVICE, L"ppDevice");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECHILD::GetDevice);
AQU_D3D_NODE_FOOTER___;

/**
* HRESULT WINAPI GetPrivateData
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_GetPrivateData, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::GetPrivateData");
AQU_D3D_NODE_COMMANDER(AQU_REFGUID, L"guid");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pDataSize");
AQU_D3D_NODE_COMMANDER(AQU_PNT_VOID, L"pData");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECHILD::GetPrivateData);
AQU_D3D_NODE_FOOTER___;

/**
* HRESULT WINAPI SetPrivateData
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_SetPrivateData, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::SetPrivateData");
AQU_D3D_NODE_COMMANDER(AQU_REFGUID, L"guid");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DataSize");
AQU_D3D_NODE_COMMANDER(AQU_PNT_VOID, L"pData");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECHILD::SetPrivateData);
AQU_D3D_NODE_FOOTER___;

/**
* HRESULT WINAPI SetPrivateDataInterface
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_SetPrivateDataInterface, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::SetPrivateDataInterface");
AQU_D3D_NODE_COMMANDER(AQU_REFGUID, L"guid");
AQU_D3D_NODE_COMMANDER(AQU_PNT_IUNKNOWN, L"pData");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECHILD::SetPrivateDataInterface);
AQU_D3D_NODE_FOOTER___;

#pragma endregion

#pragma region ID3D11DeviceContext methods
/**
* void WINAPI VSSetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_VSSetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::VSSetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::VSSetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSSetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_PSSetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::PSSetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::PSSetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSSetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_PSSetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::PSSetShader");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11PIXELSHADER, L"pPixelShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::PSSetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSSetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_PSSetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::PSSetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::PSSetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI VSSetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_VSSetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::VSSetShader");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11VERTEXSHADER, L"pVertexShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::VSSetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DrawIndexed
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_DrawIndexed, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::DrawIndexed");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"IndexCount");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartIndexLocation");
AQU_D3D_NODE_COMMANDER(AQU_INT, L"BaseVertexLocation");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::DrawIndexed);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI Draw
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_Draw, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::Draw");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"VertexCount");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartVertexLocation");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::Draw);
AQU_D3D_NODE_FOOTER___;

/**
* HRESULT WINAPI Map
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_Map, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::Map");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pResource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"Subresource");
AQU_D3D_NODE_COMMANDER(AQU_D3D11_MAP, L"MapType");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"MapFlags");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_MAPPED_SUBRESOURCE, L"pMappedResource");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::Map);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI Unmap
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_Unmap, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::Unmap");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pResource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"Subresource");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::Unmap);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSSetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_PSSetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::PSSetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::PSSetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI IASetInputLayout
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_IASetInputLayout, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::IASetInputLayout");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11INPUTLAYOUT, L"pInputLayout");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::IASetInputLayout);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI IASetVertexBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_IASetVertexBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::IASetVertexBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppVertexBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pStrides");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pOffsets");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::IASetVertexBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI IASetIndexBuffer
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_IASetIndexBuffer, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::IASetIndexBuffer");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11BUFFER, L"pIndexBuffer");
AQU_D3D_NODE_COMMANDER(AQU_DXGI_FORMAT, L"Format");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"Offset");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::IASetIndexBuffer);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DrawIndexedInstanced
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_DrawIndexedInstanced, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::DrawIndexedInstanced");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"IndexCountPerInstance");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"InstanceCount");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartIndexLocation");
AQU_D3D_NODE_COMMANDER(AQU_INT, L"BaseVertexLocation");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartInstanceLocation");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::DrawIndexedInstanced);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DrawInstanced
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_DrawInstanced, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::DrawInstanced");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"VertexCountPerInstance");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"InstanceCount");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartVertexLocation");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartInstanceLocation");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::DrawInstanced);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSSetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_GSSetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::GSSetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::GSSetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSSetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_GSSetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::GSSetShader");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11GEOMETRYSHADER, L"pShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::GSSetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI IASetPrimitiveTopology
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_IASetPrimitiveTopology, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::IASetPrimitiveTopology");
AQU_D3D_NODE_COMMANDER(AQU_D3D11_PRIMITIVE_TOPOLOGY, L"Topology");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::IASetPrimitiveTopology);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI VSSetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_VSSetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::VSSetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::VSSetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI VSSetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_VSSetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::VSSetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::VSSetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI Begin
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_Begin, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::Begin");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11ASYNCHRONOUS, L"pAsync");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::Begin);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI End
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_End, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::End");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11ASYNCHRONOUS, L"pAsync");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::End);
AQU_D3D_NODE_FOOTER___;

/**
* HRESULT WINAPI GetData
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_GetData, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::GetData");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11ASYNCHRONOUS, L"pAsync");
AQU_D3D_NODE_COMMANDER(AQU_PNT_VOID, L"pData");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DataSize");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"GetDataFlags");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::GetData);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI SetPredication
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_SetPredication, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::SetPredication");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11PREDICATE, L"pPredicate");
AQU_D3D_NODE_COMMANDER(AQU_BOOL, L"PredicateValue");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::SetPredication);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSSetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_GSSetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::GSSetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::GSSetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSSetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_GSSetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::GSSetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::GSSetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI OMSetRenderTargets
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_OMSetRenderTargets, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::OMSetRenderTargets");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11RENDERTARGETVIEW, L"ppRenderTargetViews");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11DEPTHSTENCILVIEW, L"pDepthStencilView");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::OMSetRenderTargets);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI OMSetRenderTargetsAndUnorderedAccessViews
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_OMSetRenderTargetsAndUnorderedAccessViews, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::OMSetRenderTargetsAndUnorderedAccessViews");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumRTVs");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11RENDERTARGETVIEW, L"ppRenderTargetViews");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11DEPTHSTENCILVIEW, L"pDepthStencilView");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"UAVStartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumUAVs");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11UNORDEREDACCESSVIEW, L"ppUnorderedAccessViews");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pUAVInitialCounts");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::OMSetRenderTargetsAndUnorderedAccessViews);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI OMSetBlendState
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_OMSetBlendState, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::OMSetBlendState");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11BLENDSTATE, L"pBlendState");
AQU_D3D_NODE_COMMANDER(AQU_VECTOR4F, L"BlendFactor");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"SampleMask");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::OMSetBlendState);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI OMSetDepthStencilState
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_OMSetDepthStencilState, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::OMSetDepthStencilState");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11DEPTHSTENCILSTATE, L"pDepthStencilState");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StencilRef");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::OMSetDepthStencilState);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI SOSetTargets
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_SOSetTargets, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::SOSetTargets");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppSOTargets");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pOffsets");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::SOSetTargets);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DrawAuto
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_DrawAuto, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::DrawAuto");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::DrawAuto);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DrawIndexedInstancedIndirect
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_DrawIndexedInstancedIndirect, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::DrawIndexedInstancedIndirect");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11BUFFER, L"pBufferForArgs");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"AlignedByteOffsetForArgs");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::DrawIndexedInstancedIndirect);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DrawInstancedIndirect
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_DrawInstancedIndirect, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::DrawInstancedIndirect");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11BUFFER, L"pBufferForArgs");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"AlignedByteOffsetForArgs");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::DrawInstancedIndirect);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI Dispatch
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_Dispatch, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::Dispatch");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"ThreadGroupCountX");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"ThreadGroupCountY");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"ThreadGroupCountZ");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::Dispatch);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DispatchIndirect
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_DispatchIndirect, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::DispatchIndirect");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11BUFFER, L"pBufferForArgs");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"AlignedByteOffsetForArgs");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::DispatchIndirect);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI RSSetState
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_RSSetState, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::RSSetState");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RASTERIZERSTATE, L"pRasterizerState");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::RSSetState);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI RSSetViewports
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_RSSetViewports, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::RSSetViewports");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViewports");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_VIEWPORT, L"pViewports");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::RSSetViewports);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI RSSetScissorRects
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_RSSetScissorRects, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::RSSetScissorRects");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumRects");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_RECT, L"pRects");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::RSSetScissorRects);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CopySubresourceRegion
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_CopySubresourceRegion, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::CopySubresourceRegion");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pDstResource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstSubresource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstX");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstY");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstZ");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pSrcResource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"SrcSubresource");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_BOX, L"pSrcBox");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::CopySubresourceRegion);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CopyResource
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_CopyResource, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::CopyResource");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pDstResource");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pSrcResource");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::CopyResource);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI UpdateSubresource
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_UpdateSubresource, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::UpdateSubresource");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pDstResource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstSubresource");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_BOX, L"pDstBox");
AQU_D3D_NODE_COMMANDER(AQU_PNT_VOID, L"pSrcData");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"SrcRowPitch");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"SrcDepthPitch");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::UpdateSubresource);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CopyStructureCount
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_CopyStructureCount, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::CopyStructureCount");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11BUFFER, L"pDstBuffer");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstAlignedByteOffset");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11UNORDEREDACCESSVIEW, L"pSrcView");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::CopyStructureCount);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI ClearRenderTargetView
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_ClearRenderTargetView, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::ClearRenderTargetView");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RENDERTARGETVIEW, L"pRenderTargetView");
AQU_D3D_NODE_COMMANDER(AQU_VECTOR4F, L"ColorRGBA");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::ClearRenderTargetView);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI ClearUnorderedAccessViewUint
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_ClearUnorderedAccessViewUint, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::ClearUnorderedAccessViewUint");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11UNORDEREDACCESSVIEW, L"pUnorderedAccessView");
AQU_D3D_NODE_COMMANDER(AQU_VECTOR4D, L"Values");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::ClearUnorderedAccessViewUint);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI ClearUnorderedAccessViewFloat
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_ClearUnorderedAccessViewFloat, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::ClearUnorderedAccessViewFloat");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11UNORDEREDACCESSVIEW, L"pUnorderedAccessView");
AQU_D3D_NODE_COMMANDER(AQU_VECTOR4F, L"Values");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::ClearUnorderedAccessViewFloat);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI ClearDepthStencilView
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_ClearDepthStencilView, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::ClearDepthStencilView");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11DEPTHSTENCILVIEW, L"pDepthStencilView");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"ClearFlags");
AQU_D3D_NODE_COMMANDER(AQU_FLOAT, L"Depth");
AQU_D3D_NODE_COMMANDER(AQU_BYTE, L"Stencil");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::ClearDepthStencilView);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GenerateMips
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_GenerateMips, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::GenerateMips");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11SHADERRESOURCEVIEW, L"pShaderResourceView");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::GenerateMips);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI SetResourceMinLOD
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_SetResourceMinLOD, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::SetResourceMinLOD");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pResource");
AQU_D3D_NODE_COMMANDER(AQU_FLOAT, L"MinLOD");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::SetResourceMinLOD);
AQU_D3D_NODE_FOOTER___;

/**
* FLOAT WINAPI GetResourceMinLOD
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_GetResourceMinLOD, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::GetResourceMinLOD");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pResource");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::GetResourceMinLOD);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI ResolveSubresource
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_ResolveSubresource, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::ResolveSubresource");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pDstResource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstSubresource");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pSrcResource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"SrcSubresource");
AQU_D3D_NODE_COMMANDER(AQU_DXGI_FORMAT, L"Format");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::ResolveSubresource);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI ExecuteCommandList
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_ExecuteCommandList, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::ExecuteCommandList");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11COMMANDLIST, L"pCommandList");
AQU_D3D_NODE_COMMANDER(AQU_BOOL, L"RestoreContextState");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::ExecuteCommandList);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSSetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_HSSetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::HSSetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::HSSetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSSetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_HSSetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::HSSetShader");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11HULLSHADER, L"pHullShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::HSSetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSSetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_HSSetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::HSSetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::HSSetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSSetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_HSSetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::HSSetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::HSSetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSSetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_DSSetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::DSSetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::DSSetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSSetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_DSSetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::DSSetShader");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11DOMAINSHADER, L"pDomainShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::DSSetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSSetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_DSSetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::DSSetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::DSSetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSSetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_DSSetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::DSSetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::DSSetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSSetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_CSSetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::CSSetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::CSSetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSSetUnorderedAccessViews
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_CSSetUnorderedAccessViews, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::CSSetUnorderedAccessViews");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumUAVs");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11UNORDEREDACCESSVIEW, L"ppUnorderedAccessViews");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pUAVInitialCounts");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::CSSetUnorderedAccessViews);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSSetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_CSSetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::CSSetShader");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11COMPUTESHADER, L"pComputeShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::CSSetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSSetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_CSSetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::CSSetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::CSSetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSSetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_CSSetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::CSSetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::CSSetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI VSGetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_VSGetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::VSGetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::VSGetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSGetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_PSGetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::PSGetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::PSGetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSGetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_PSGetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::PSGetShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11PIXELSHADER, L"ppPixelShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::PSGetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSGetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_PSGetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::PSGetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::PSGetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI VSGetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_VSGetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::VSGetShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11VERTEXSHADER, L"ppVertexShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::VSGetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSGetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_PSGetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::PSGetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::PSGetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI IAGetInputLayout
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_IAGetInputLayout, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::IAGetInputLayout");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11INPUTLAYOUT, L"ppInputLayout");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::IAGetInputLayout);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI IAGetVertexBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_IAGetVertexBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::IAGetVertexBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppVertexBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pStrides");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pOffsets");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::IAGetVertexBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI IAGetIndexBuffer
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_IAGetIndexBuffer, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::IAGetIndexBuffer");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"pIndexBuffer");
AQU_D3D_NODE_COMMANDER(AQU_PNT_DXGI_FORMAT, L"Format");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"Offset");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::IAGetIndexBuffer);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSGetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_GSGetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::GSGetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::GSGetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSGetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_GSGetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::GSGetShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11GEOMETRYSHADER, L"ppGeometryShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::GSGetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI IAGetPrimitiveTopology
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_IAGetPrimitiveTopology, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::IAGetPrimitiveTopology");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_PRIMITIVE_TOPOLOGY, L"pTopology");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::IAGetPrimitiveTopology);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI VSGetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_VSGetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::VSGetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::VSGetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI VSGetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_VSGetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::VSGetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::VSGetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GetPredication
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_GetPredication, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::GetPredication");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11PREDICATE, L"ppPredicate");
AQU_D3D_NODE_COMMANDER(AQU_PNT_BOOL, L"pPredicateValue");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::GetPredication);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSGetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_GSGetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::GSGetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::GSGetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSGetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_GSGetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::GSGetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::GSGetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI OMGetRenderTargets
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_OMGetRenderTargets, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::OMGetRenderTargets");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11RENDERTARGETVIEW, L"ppRenderTargetViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11DEPTHSTENCILVIEW, L"ppDepthStencilView");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::OMGetRenderTargets);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI OMGetRenderTargetsAndUnorderedAccessViews
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_OMGetRenderTargetsAndUnorderedAccessViews, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::OMGetRenderTargetsAndUnorderedAccessViews");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumRTVs");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11RENDERTARGETVIEW, L"ppRenderTargetViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11DEPTHSTENCILVIEW, L"ppDepthStencilView");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"UAVStartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumUAVs");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11UNORDEREDACCESSVIEW, L"ppUnorderedAccessViews");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::OMGetRenderTargetsAndUnorderedAccessViews);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI OMGetBlendState
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_OMGetBlendState, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::OMGetBlendState");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BLENDSTATE, L"ppBlendState");
AQU_D3D_NODE_COMMANDER(AQU_PNT_FLOAT, L"BlendFactor");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pSampleMask");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::OMGetBlendState);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI OMGetDepthStencilState
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_OMGetDepthStencilState, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::OMGetDepthStencilState");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11DEPTHSTENCILSTATE, L"ppDepthStencilState");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pStencilRef");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::OMGetDepthStencilState);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI SOGetTargets
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_SOGetTargets, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::SOGetTargets");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppSOTargets");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::SOGetTargets);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI RSGetState
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_RSGetState, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::RSGetState");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11RASTERIZERSTATE, L"ppRasterizerState");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::RSGetState);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI RSGetViewports
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_RSGetViewports, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::RSGetViewports");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumViewports");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_VIEWPORT, L"pViewports");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::RSGetViewports);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI RSGetScissorRects
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_RSGetScissorRects, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::RSGetScissorRects");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumRects");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_RECT, L"pRects");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::RSGetScissorRects);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSGetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_HSGetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::HSGetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::HSGetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSGetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_HSGetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::HSGetShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11HULLSHADER, L"ppHullShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::HSGetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSGetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_HSGetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::HSGetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::HSGetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSGetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_HSGetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::HSGetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::HSGetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSGetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_DSGetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::DSGetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::DSGetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSGetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_DSGetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::DSGetShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11DOMAINSHADER, L"ppDomainShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::DSGetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSGetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_DSGetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::DSGetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::DSGetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSGetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_DSGetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::DSGetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::DSGetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSGetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_CSGetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::CSGetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::CSGetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSGetUnorderedAccessViews
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_CSGetUnorderedAccessViews, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::CSGetUnorderedAccessViews");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumUAVs");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11UNORDEREDACCESSVIEW, L"ppUnorderedAccessViews");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::CSGetUnorderedAccessViews);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSGetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_CSGetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::CSGetShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11COMPUTESHADER, L"ppComputeShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::CSGetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSGetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_CSGetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::CSGetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::CSGetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSGetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_CSGetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::CSGetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::CSGetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI ClearState
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_ClearState, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::ClearState");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::ClearState);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI Flush
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_Flush, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::Flush");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::Flush);
AQU_D3D_NODE_FOOTER___;

/**
* D3D11_DEVICE_CONTEXT_TYPE WINAPI GetType
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_GetType, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::GetType");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::GetType);
AQU_D3D_NODE_FOOTER___;

/**
* UINT WINAPI GetContextFlags
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_GetContextFlags, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::GetContextFlags");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::GetContextFlags);
AQU_D3D_NODE_FOOTER___;

/**
* HRESULT WINAPI FinishCommandList
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext_FinishCommandList, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext::FinishCommandList");
AQU_D3D_NODE_COMMANDER(AQU_BOOL, L"RestoreDeferredContextState");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11COMMANDLIST, L"ppCommandList");
AQU_D3D_NODE_METHOD___(DirectX_11, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext, VMT_ID3D11DEVICECONTEXT::FinishCommandList);
AQU_D3D_NODE_FOOTER___;

#pragma endregion

#pragma region ID3D11DeviceContext node provider method

/**
* Node provider class.
***/
class NOD_ID3D11DeviceContext
{
public:
	/**
	* Provides ID3D11DeviceContext node by index.
	***/
	NOD_Basic* Get_ID3D11DeviceContext_Node(UINT dwIndex, LONG nX, LONG nY)
	{
		if (dwIndex > (UINT)VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::FinishCommandList) return nullptr;
		if (dwIndex <= (UINT)VMT_IUNKNOWN::Release) return Get_ID3D11DeviceContext_Node((VMT_IUNKNOWN::VMT_IUnknown)dwIndex, nX, nY);
		if (dwIndex <= (UINT)VMT_ID3D11DEVICECHILD::SetPrivateDataInterface) return Get_ID3D11DeviceContext_Node((VMT_ID3D11DEVICECHILD::VMT_ID3D11DeviceChild)dwIndex, nX, nY);
		return Get_ID3D11DeviceContext_Node((VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext)dwIndex, nX, nY);
	}

	/**
	* Provides IUnknown node by enumeration.
	***/
	NOD_Basic* Get_ID3D11DeviceContext_Node(VMT_IUNKNOWN::VMT_IUnknown eMethod, LONG nX, LONG nY)
	{
		switch (eMethod)
		{
		case VMT_IUNKNOWN::VMT_IUnknown::QueryInterface:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_QueryInterface(nX, nY);
			break;
		case VMT_IUNKNOWN::VMT_IUnknown::AddRef:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_AddRef(nX, nY);
			break;
		case VMT_IUNKNOWN::VMT_IUnknown::Release:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_Release(nX, nY);
			break;
		default:
			break;
		}

		return nullptr;
	}

	/**
	* Provides ID3D11DeviceChild node by enumeration.
	***/
	NOD_Basic* Get_ID3D11DeviceContext_Node(VMT_ID3D11DEVICECHILD::VMT_ID3D11DeviceChild eMethod, LONG nX, LONG nY)
	{
		switch (eMethod)
		{
		case VMT_ID3D11DEVICECHILD::VMT_ID3D11DeviceChild::GetDevice:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_GetDevice(nX, nY);
			break;
		case VMT_ID3D11DEVICECHILD::VMT_ID3D11DeviceChild::GetPrivateData:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_GetPrivateData(nX, nY);
			break;
		case VMT_ID3D11DEVICECHILD::VMT_ID3D11DeviceChild::SetPrivateData:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_SetPrivateData(nX, nY);
			break;
		case VMT_ID3D11DEVICECHILD::VMT_ID3D11DeviceChild::SetPrivateDataInterface:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_SetPrivateDataInterface(nX, nY);
			break;
		default:
			break;
		}

		return nullptr;
	}

	/**
	* Provides ID3D11DeviceContext node by enumeration.
	***/
	NOD_Basic* Get_ID3D11DeviceContext_Node(VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext eMethod, LONG nX, LONG nY)
	{
		switch (eMethod)
		{
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::VSSetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_VSSetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::PSSetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_PSSetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::PSSetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_PSSetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::PSSetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_PSSetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::VSSetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_VSSetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DrawIndexed:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_DrawIndexed(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::Draw:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_Draw(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::Map:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_Map(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::Unmap:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_Unmap(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::PSSetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_PSSetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::IASetInputLayout:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_IASetInputLayout(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::IASetVertexBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_IASetVertexBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::IASetIndexBuffer:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_IASetIndexBuffer(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DrawIndexedInstanced:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_DrawIndexedInstanced(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DrawInstanced:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_DrawInstanced(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GSSetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_GSSetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GSSetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_GSSetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::IASetPrimitiveTopology:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_IASetPrimitiveTopology(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::VSSetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_VSSetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::VSSetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_VSSetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::Begin:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_Begin(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::End:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_End(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GetData:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_GetData(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::SetPredication:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_SetPredication(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GSSetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_GSSetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GSSetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_GSSetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::OMSetRenderTargets:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_OMSetRenderTargets(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::OMSetRenderTargetsAndUnorderedAccessViews:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_OMSetRenderTargetsAndUnorderedAccessViews(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::OMSetBlendState:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_OMSetBlendState(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::OMSetDepthStencilState:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_OMSetDepthStencilState(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::SOSetTargets:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_SOSetTargets(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DrawAuto:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_DrawAuto(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DrawIndexedInstancedIndirect:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_DrawIndexedInstancedIndirect(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DrawInstancedIndirect:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_DrawInstancedIndirect(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::Dispatch:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_Dispatch(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DispatchIndirect:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_DispatchIndirect(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::RSSetState:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_RSSetState(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::RSSetViewports:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_RSSetViewports(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::RSSetScissorRects:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_RSSetScissorRects(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CopySubresourceRegion:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_CopySubresourceRegion(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CopyResource:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_CopyResource(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::UpdateSubresource:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_UpdateSubresource(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CopyStructureCount:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_CopyStructureCount(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::ClearRenderTargetView:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_ClearRenderTargetView(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::ClearUnorderedAccessViewUint:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_ClearUnorderedAccessViewUint(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::ClearUnorderedAccessViewFloat:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_ClearUnorderedAccessViewFloat(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::ClearDepthStencilView:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_ClearDepthStencilView(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GenerateMips:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_GenerateMips(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::SetResourceMinLOD:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_SetResourceMinLOD(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GetResourceMinLOD:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_GetResourceMinLOD(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::ResolveSubresource:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_ResolveSubresource(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::ExecuteCommandList:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_ExecuteCommandList(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::HSSetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_HSSetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::HSSetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_HSSetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::HSSetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_HSSetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::HSSetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_HSSetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DSSetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_DSSetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DSSetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_DSSetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DSSetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_DSSetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DSSetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_DSSetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSSetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_CSSetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSSetUnorderedAccessViews:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_CSSetUnorderedAccessViews(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSSetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_CSSetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSSetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_CSSetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSSetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_CSSetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::VSGetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_VSGetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::PSGetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_PSGetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::PSGetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_PSGetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::PSGetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_PSGetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::VSGetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_VSGetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::PSGetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_PSGetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::IAGetInputLayout:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_IAGetInputLayout(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::IAGetVertexBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_IAGetVertexBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::IAGetIndexBuffer:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_IAGetIndexBuffer(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GSGetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_GSGetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GSGetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_GSGetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::IAGetPrimitiveTopology:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_IAGetPrimitiveTopology(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::VSGetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_VSGetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::VSGetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_VSGetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GetPredication:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_GetPredication(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GSGetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_GSGetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GSGetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_GSGetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::OMGetRenderTargets:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_OMGetRenderTargets(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::OMGetRenderTargetsAndUnorderedAccessViews:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_OMGetRenderTargetsAndUnorderedAccessViews(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::OMGetBlendState:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_OMGetBlendState(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::OMGetDepthStencilState:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_OMGetDepthStencilState(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::SOGetTargets:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_SOGetTargets(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::RSGetState:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_RSGetState(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::RSGetViewports:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_RSGetViewports(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::RSGetScissorRects:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_RSGetScissorRects(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::HSGetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_HSGetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::HSGetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_HSGetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::HSGetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_HSGetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::HSGetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_HSGetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DSGetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_DSGetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DSGetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_DSGetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DSGetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_DSGetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DSGetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_DSGetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSGetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_CSGetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSGetUnorderedAccessViews:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_CSGetUnorderedAccessViews(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSGetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_CSGetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSGetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_CSGetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSGetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_CSGetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::ClearState:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_ClearState(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::Flush:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_Flush(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GetType:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_GetType(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GetContextFlags:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_GetContextFlags(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::FinishCommandList:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext_FinishCommandList(nX, nY);
			break;
		default:
			break;
		}

		return nullptr;
	}

};
#pragma endregion

#endif
