/********************************************************************
Vireio Perception : Open-Source Stereoscopic 3D Driver
Copyright (C) 2012 Andres Hernandez

Aquilinus : Vireio Perception 3D Modification Studio 
Copyright © 2014 Denis Reischl

Vireio Perception Version History:
v1.0.0 2012 by Andres Hernandez
v1.0.X 2013 by John Hicks, Neil Schneider
v1.1.x 2013 by Primary Coding Author: Chris Drain
Team Support: John Hicks, Phil Larkson, Neil Schneider
v2.0.x 2013 by Denis Reischl, Neil Schneider, Joshua Brown
v2.0.4 to v3.0.x 2014-2015 by Grant Bagwell, Simon Brown and Neil Schneider
v4.0.x 2015 by Denis Reischl, Grant Bagwell, Simon Brown and Neil Schneider

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
********************************************************************/
#ifndef NOD_ID3D11DEVICECONTEXT1
#define NOD_ID3D11DEVICECONTEXT1

#include"VMT_ID3D11DeviceContext1.h"

#pragma region IUnknown methods
/**
* HRESULT WINAPI QueryInterface
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_QueryInterface, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::QueryInterface");
AQU_D3D_NODE_COMMANDER(AQU_REFIID, L"riid");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_VOID, L"ppvObject");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_IUNKNOWN::QueryInterface);
AQU_D3D_NODE_FOOTER___;

/**
* ULONG WINAPI AddRef
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_AddRef, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::AddRef");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_IUNKNOWN::AddRef);
AQU_D3D_NODE_FOOTER___;

/**
* ULONG WINAPI Release
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_Release, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::Release");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_IUNKNOWN::Release);
AQU_D3D_NODE_FOOTER___;

#pragma endregion

#pragma region ID3D11DeviceContext methods
/**
* void WINAPI VSSetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_VSSetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::VSSetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::VSSetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSSetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_PSSetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::PSSetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::PSSetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSSetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_PSSetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::PSSetShader");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11PIXELSHADER, L"pPixelShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::PSSetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSSetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_PSSetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::PSSetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::PSSetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI VSSetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_VSSetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::VSSetShader");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11VERTEXSHADER, L"pVertexShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::VSSetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DrawIndexed
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DrawIndexed, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DrawIndexed");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"IndexCount");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartIndexLocation");
AQU_D3D_NODE_COMMANDER(AQU_INT, L"BaseVertexLocation");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::DrawIndexed);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI Draw
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_Draw, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::Draw");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"VertexCount");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartVertexLocation");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::Draw);
AQU_D3D_NODE_FOOTER___;

/**
* HRESULT WINAPI Map
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_Map, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::Map");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pResource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"Subresource");
AQU_D3D_NODE_COMMANDER(AQU_D3D11_MAP, L"MapType");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"MapFlags");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_MAPPED_SUBRESOURCE, L"pMappedResource");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::Map);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI Unmap
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_Unmap, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::Unmap");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pResource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"Subresource");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::Unmap);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSSetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_PSSetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::PSSetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::PSSetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI IASetInputLayout
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_IASetInputLayout, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::IASetInputLayout");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11INPUTLAYOUT, L"pInputLayout");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::IASetInputLayout);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI IASetVertexBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_IASetVertexBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::IASetVertexBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppVertexBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pStrides");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pOffsets");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::IASetVertexBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI IASetIndexBuffer
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_IASetIndexBuffer, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::IASetIndexBuffer");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11BUFFER, L"pIndexBuffer");
AQU_D3D_NODE_COMMANDER(AQU_DXGI_FORMAT, L"Format");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"Offset");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::IASetIndexBuffer);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DrawIndexedInstanced
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DrawIndexedInstanced, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DrawIndexedInstanced");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"IndexCountPerInstance");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"InstanceCount");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartIndexLocation");
AQU_D3D_NODE_COMMANDER(AQU_INT, L"BaseVertexLocation");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartInstanceLocation");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::DrawIndexedInstanced);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DrawInstanced
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DrawInstanced, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DrawInstanced");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"VertexCountPerInstance");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"InstanceCount");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartVertexLocation");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartInstanceLocation");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::DrawInstanced);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSSetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_GSSetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::GSSetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::GSSetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSSetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_GSSetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::GSSetShader");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11GEOMETRYSHADER, L"pShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::GSSetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI IASetPrimitiveTopology
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_IASetPrimitiveTopology, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::IASetPrimitiveTopology");
AQU_D3D_NODE_COMMANDER(AQU_D3D11_PRIMITIVE_TOPOLOGY, L"Topology");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::IASetPrimitiveTopology);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI VSSetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_VSSetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::VSSetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::VSSetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI VSSetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_VSSetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::VSSetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::VSSetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI Begin
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_Begin, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::Begin");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11ASYNCHRONOUS, L"pAsync");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::Begin);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI End
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_End, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::End");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11ASYNCHRONOUS, L"pAsync");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::End);
AQU_D3D_NODE_FOOTER___;

/**
* HRESULT WINAPI GetData
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_GetData, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::GetData");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11ASYNCHRONOUS, L"pAsync");
AQU_D3D_NODE_COMMANDER(AQU_PNT_VOID, L"pData");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DataSize");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"GetDataFlags");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::GetData);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI SetPredication
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_SetPredication, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::SetPredication");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11PREDICATE, L"pPredicate");
AQU_D3D_NODE_COMMANDER(AQU_BOOL, L"PredicateValue");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::SetPredication);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSSetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_GSSetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::GSSetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::GSSetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSSetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_GSSetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::GSSetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::GSSetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI OMSetRenderTargets
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_OMSetRenderTargets, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::OMSetRenderTargets");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11RENDERTARGETVIEW, L"ppRenderTargetViews");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11DEPTHSTENCILVIEW, L"pDepthStencilView");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::OMSetRenderTargets);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI OMSetRenderTargetsAndUnorderedAccessViews
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_OMSetRenderTargetsAndUnorderedAccessViews, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::OMSetRenderTargetsAndUnorderedAccessViews");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumRTVs");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11RENDERTARGETVIEW, L"ppRenderTargetViews");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11DEPTHSTENCILVIEW, L"pDepthStencilView");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"UAVStartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumUAVs");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11UNORDEREDACCESSVIEW, L"ppUnorderedAccessViews");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pUAVInitialCounts");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::OMSetRenderTargetsAndUnorderedAccessViews);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI OMSetBlendState
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_OMSetBlendState, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::OMSetBlendState");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11BLENDSTATE, L"pBlendState");
AQU_D3D_NODE_COMMANDER(AQU_PNT_FLOAT, L"BlendFactor");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"SampleMask");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::OMSetBlendState);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI OMSetDepthStencilState
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_OMSetDepthStencilState, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::OMSetDepthStencilState");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11DEPTHSTENCILSTATE, L"pDepthStencilState");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StencilRef");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::OMSetDepthStencilState);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI SOSetTargets
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_SOSetTargets, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::SOSetTargets");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppSOTargets");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pOffsets");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::SOSetTargets);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DrawAuto
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DrawAuto, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DrawAuto");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::DrawAuto);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DrawIndexedInstancedIndirect
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DrawIndexedInstancedIndirect, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DrawIndexedInstancedIndirect");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11BUFFER, L"pBufferForArgs");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"AlignedByteOffsetForArgs");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::DrawIndexedInstancedIndirect);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DrawInstancedIndirect
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DrawInstancedIndirect, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DrawInstancedIndirect");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11BUFFER, L"pBufferForArgs");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"AlignedByteOffsetForArgs");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::DrawInstancedIndirect);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI Dispatch
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_Dispatch, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::Dispatch");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"ThreadGroupCountX");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"ThreadGroupCountY");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"ThreadGroupCountZ");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::Dispatch);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DispatchIndirect
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DispatchIndirect, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DispatchIndirect");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11BUFFER, L"pBufferForArgs");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"AlignedByteOffsetForArgs");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::DispatchIndirect);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI RSSetState
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_RSSetState, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::RSSetState");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RASTERIZERSTATE, L"pRasterizerState");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::RSSetState);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI RSSetViewports
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_RSSetViewports, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::RSSetViewports");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViewports");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_VIEWPORT, L"pViewports");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::RSSetViewports);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI RSSetScissorRects
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_RSSetScissorRects, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::RSSetScissorRects");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumRects");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_RECT, L"pRects");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::RSSetScissorRects);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CopySubresourceRegion
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_CopySubresourceRegion, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::CopySubresourceRegion");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pDstResource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstSubresource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstX");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstY");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstZ");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pSrcResource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"SrcSubresource");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_BOX, L"pSrcBox");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::CopySubresourceRegion);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CopyResource
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_CopyResource, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::CopyResource");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pDstResource");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pSrcResource");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::CopyResource);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI UpdateSubresource
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_UpdateSubresource, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::UpdateSubresource");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pDstResource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstSubresource");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_BOX, L"pDstBox");
AQU_D3D_NODE_COMMANDER(AQU_PNT_VOID, L"pSrcData");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"SrcRowPitch");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"SrcDepthPitch");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::UpdateSubresource);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CopyStructureCount
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_CopyStructureCount, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::CopyStructureCount");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11BUFFER, L"pDstBuffer");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstAlignedByteOffset");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11UNORDEREDACCESSVIEW, L"pSrcView");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::CopyStructureCount);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI ClearRenderTargetView
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_ClearRenderTargetView, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::ClearRenderTargetView");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RENDERTARGETVIEW, L"pRenderTargetView");
AQU_D3D_NODE_COMMANDER(AQU_PNT_FLOAT, L"ColorRGBA");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::ClearRenderTargetView);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI ClearUnorderedAccessViewUint
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_ClearUnorderedAccessViewUint, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::ClearUnorderedAccessViewUint");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11UNORDEREDACCESSVIEW, L"pUnorderedAccessView");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"Values");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::ClearUnorderedAccessViewUint);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI ClearUnorderedAccessViewFloat
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_ClearUnorderedAccessViewFloat, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::ClearUnorderedAccessViewFloat");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11UNORDEREDACCESSVIEW, L"pUnorderedAccessView");
AQU_D3D_NODE_COMMANDER(AQU_PNT_FLOAT, L"Values");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::ClearUnorderedAccessViewFloat);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI ClearDepthStencilView
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_ClearDepthStencilView, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::ClearDepthStencilView");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11DEPTHSTENCILVIEW, L"pDepthStencilView");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"ClearFlags");
AQU_D3D_NODE_COMMANDER(AQU_FLOAT, L"Depth");
AQU_D3D_NODE_COMMANDER(AQU_BYTE, L"Stencil");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::ClearDepthStencilView);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GenerateMips
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_GenerateMips, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::GenerateMips");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11SHADERRESOURCEVIEW, L"pShaderResourceView");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::GenerateMips);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI SetResourceMinLOD
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_SetResourceMinLOD, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::SetResourceMinLOD");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pResource");
AQU_D3D_NODE_COMMANDER(AQU_FLOAT, L"MinLOD");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::SetResourceMinLOD);
AQU_D3D_NODE_FOOTER___;

/**
* FLOAT WINAPI GetResourceMinLOD
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_GetResourceMinLOD, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::GetResourceMinLOD");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pResource");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::GetResourceMinLOD);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI ResolveSubresource
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_ResolveSubresource, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::ResolveSubresource");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pDstResource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstSubresource");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pSrcResource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"SrcSubresource");
AQU_D3D_NODE_COMMANDER(AQU_DXGI_FORMAT, L"Format");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::ResolveSubresource);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI ExecuteCommandList
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_ExecuteCommandList, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::ExecuteCommandList");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11COMMANDLIST, L"pCommandList");
AQU_D3D_NODE_COMMANDER(AQU_BOOL, L"RestoreContextState");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::ExecuteCommandList);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSSetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_HSSetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::HSSetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::HSSetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSSetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_HSSetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::HSSetShader");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11HULLSHADER, L"pHullShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::HSSetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSSetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_HSSetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::HSSetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::HSSetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSSetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_HSSetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::HSSetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::HSSetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSSetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DSSetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DSSetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::DSSetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSSetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DSSetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DSSetShader");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11DOMAINSHADER, L"pDomainShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::DSSetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSSetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DSSetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DSSetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::DSSetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSSetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DSSetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DSSetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::DSSetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSSetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_CSSetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::CSSetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::CSSetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSSetUnorderedAccessViews
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_CSSetUnorderedAccessViews, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::CSSetUnorderedAccessViews");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumUAVs");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11UNORDEREDACCESSVIEW, L"ppUnorderedAccessViews");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pUAVInitialCounts");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::CSSetUnorderedAccessViews);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSSetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_CSSetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::CSSetShader");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11COMPUTESHADER, L"pComputeShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::CSSetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSSetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_CSSetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::CSSetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::CSSetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSSetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_CSSetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::CSSetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::CSSetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI VSGetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_VSGetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::VSGetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::VSGetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSGetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_PSGetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::PSGetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::PSGetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSGetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_PSGetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::PSGetShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11PIXELSHADER, L"ppPixelShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::PSGetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSGetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_PSGetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::PSGetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::PSGetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI VSGetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_VSGetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::VSGetShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11VERTEXSHADER, L"ppVertexShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::VSGetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSGetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_PSGetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::PSGetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::PSGetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI IAGetInputLayout
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_IAGetInputLayout, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::IAGetInputLayout");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11INPUTLAYOUT, L"ppInputLayout");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::IAGetInputLayout);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI IAGetVertexBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_IAGetVertexBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::IAGetVertexBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppVertexBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pStrides");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pOffsets");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::IAGetVertexBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI IAGetIndexBuffer
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_IAGetIndexBuffer, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::IAGetIndexBuffer");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"pIndexBuffer");
AQU_D3D_NODE_COMMANDER(AQU_PNT_DXGI_FORMAT, L"Format");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"Offset");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::IAGetIndexBuffer);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSGetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_GSGetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::GSGetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::GSGetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSGetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_GSGetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::GSGetShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11GEOMETRYSHADER, L"ppGeometryShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::GSGetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI IAGetPrimitiveTopology
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_IAGetPrimitiveTopology, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::IAGetPrimitiveTopology");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_PRIMITIVE_TOPOLOGY, L"pTopology");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::IAGetPrimitiveTopology);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI VSGetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_VSGetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::VSGetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::VSGetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI VSGetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_VSGetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::VSGetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::VSGetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GetPredication
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_GetPredication, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::GetPredication");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11PREDICATE, L"ppPredicate");
AQU_D3D_NODE_COMMANDER(AQU_PNT_BOOL, L"pPredicateValue");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::GetPredication);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSGetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_GSGetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::GSGetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::GSGetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSGetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_GSGetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::GSGetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::GSGetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI OMGetRenderTargets
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_OMGetRenderTargets, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::OMGetRenderTargets");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11RENDERTARGETVIEW, L"ppRenderTargetViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11DEPTHSTENCILVIEW, L"ppDepthStencilView");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::OMGetRenderTargets);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI OMGetRenderTargetsAndUnorderedAccessViews
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_OMGetRenderTargetsAndUnorderedAccessViews, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::OMGetRenderTargetsAndUnorderedAccessViews");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumRTVs");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11RENDERTARGETVIEW, L"ppRenderTargetViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11DEPTHSTENCILVIEW, L"ppDepthStencilView");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"UAVStartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumUAVs");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11UNORDEREDACCESSVIEW, L"ppUnorderedAccessViews");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::OMGetRenderTargetsAndUnorderedAccessViews);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI OMGetBlendState
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_OMGetBlendState, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::OMGetBlendState");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BLENDSTATE, L"ppBlendState");
AQU_D3D_NODE_COMMANDER(AQU_PNT_FLOAT, L"BlendFactor");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pSampleMask");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::OMGetBlendState);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI OMGetDepthStencilState
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_OMGetDepthStencilState, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::OMGetDepthStencilState");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11DEPTHSTENCILSTATE, L"ppDepthStencilState");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pStencilRef");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::OMGetDepthStencilState);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI SOGetTargets
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_SOGetTargets, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::SOGetTargets");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppSOTargets");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::SOGetTargets);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI RSGetState
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_RSGetState, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::RSGetState");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11RASTERIZERSTATE, L"ppRasterizerState");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::RSGetState);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI RSGetViewports
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_RSGetViewports, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::RSGetViewports");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumViewports");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_VIEWPORT, L"pViewports");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::RSGetViewports);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI RSGetScissorRects
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_RSGetScissorRects, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::RSGetScissorRects");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumRects");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_RECT, L"pRects");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::RSGetScissorRects);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSGetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_HSGetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::HSGetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::HSGetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSGetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_HSGetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::HSGetShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11HULLSHADER, L"ppHullShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::HSGetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSGetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_HSGetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::HSGetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::HSGetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSGetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_HSGetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::HSGetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::HSGetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSGetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DSGetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DSGetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::DSGetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSGetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DSGetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DSGetShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11DOMAINSHADER, L"ppDomainShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::DSGetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSGetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DSGetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DSGetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::DSGetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSGetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DSGetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DSGetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::DSGetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSGetShaderResources
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_CSGetShaderResources, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::CSGetShaderResources");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumViews");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SHADERRESOURCEVIEW, L"ppShaderResourceViews");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::CSGetShaderResources);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSGetUnorderedAccessViews
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_CSGetUnorderedAccessViews, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::CSGetUnorderedAccessViews");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumUAVs");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11UNORDEREDACCESSVIEW, L"ppUnorderedAccessViews");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::CSGetUnorderedAccessViews);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSGetShader
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_CSGetShader, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::CSGetShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11COMPUTESHADER, L"ppComputeShader");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11CLASSINSTANCE, L"ppClassInstances");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumClassInstances");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::CSGetShader);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSGetSamplers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_CSGetSamplers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::CSGetSamplers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumSamplers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11SAMPLERSTATE, L"ppSamplers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::CSGetSamplers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSGetConstantBuffers
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_CSGetConstantBuffers, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::CSGetConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::CSGetConstantBuffers);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI ClearState
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_ClearState, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::ClearState");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::ClearState);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI Flush
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_Flush, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::Flush");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::Flush);
AQU_D3D_NODE_FOOTER___;

/**
* D3D11_DEVICE_CONTEXT_TYPE WINAPI GetType
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_GetType, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::GetType");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::GetType);
AQU_D3D_NODE_FOOTER___;

/**
* UINT WINAPI GetContextFlags
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_GetContextFlags, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::GetContextFlags");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::GetContextFlags);
AQU_D3D_NODE_FOOTER___;

/**
* HRESULT WINAPI FinishCommandList
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_FinishCommandList, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::FinishCommandList");
AQU_D3D_NODE_COMMANDER(AQU_BOOL, L"RestoreDeferredContextState");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11COMMANDLIST, L"ppCommandList");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT::FinishCommandList);
AQU_D3D_NODE_FOOTER___;

#pragma endregion

#pragma region ID3D11DeviceContext1 methods
/**
* void WINAPI CopySubresourceRegion1
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_CopySubresourceRegion1, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::CopySubresourceRegion1");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pDstResource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstSubresource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstX");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstY");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstZ");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pSrcResource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"SrcSubresource");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_BOX, L"pSrcBox");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"CopyFlags");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::CopySubresourceRegion1);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI UpdateSubresource1
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_UpdateSubresource1, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::UpdateSubresource1");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pDstResource");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"DstSubresource");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_BOX, L"pDstBox");
AQU_D3D_NODE_COMMANDER(AQU_PNT_VOID, L"pSrcData");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"SrcRowPitch");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"SrcDepthPitch");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"CopyFlags");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::UpdateSubresource1);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DiscardResource
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DiscardResource, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DiscardResource");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11RESOURCE, L"pResource");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::DiscardResource);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DiscardView
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DiscardView, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DiscardView");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11VIEW, L"pResourceView");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::DiscardView);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI VSSetConstantBuffers1
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_VSSetConstantBuffers1, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::VSSetConstantBuffers1");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pFirstConstant");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumConstants");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::VSSetConstantBuffers1);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSSetConstantBuffers1
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_HSSetConstantBuffers1, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::HSSetConstantBuffers1");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pFirstConstant");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumConstants");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::HSSetConstantBuffers1);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSSetConstantBuffers1
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DSSetConstantBuffers1, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DSSetConstantBuffers1");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pFirstConstant");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumConstants");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::DSSetConstantBuffers1);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSSetConstantBuffers1
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_GSSetConstantBuffers1, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::GSSetConstantBuffers1");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pFirstConstant");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumConstants");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::GSSetConstantBuffers1);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSSetConstantBuffers1
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_PSSetConstantBuffers1, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::PSSetConstantBuffers1");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pFirstConstant");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumConstants");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::PSSetConstantBuffers1);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSSetConstantBuffers1
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_CSSetConstantBuffers1, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::CSSetConstantBuffers1");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pFirstConstant");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumConstants");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::CSSetConstantBuffers1);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI VSGetConstantBuffers1
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_VSGetConstantBuffers1, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::VSGetConstantBuffers1");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pFirstConstant");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumConstants");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::VSGetConstantBuffers1);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI HSGetConstantBuffers1
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_HSGetConstantBuffers1, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::HSGetConstantBuffers1");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pFirstConstant");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumConstants");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::HSGetConstantBuffers1);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DSGetConstantBuffers1
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DSGetConstantBuffers1, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DSGetConstantBuffers1");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pFirstConstant");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumConstants");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::DSGetConstantBuffers1);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI GSGetConstantBuffers1
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_GSGetConstantBuffers1, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::GSGetConstantBuffers1");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pFirstConstant");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumConstants");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::GSGetConstantBuffers1);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI PSGetConstantBuffers1
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_PSGetConstantBuffers1, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::PSGetConstantBuffers1");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pFirstConstant");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumConstants");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::PSGetConstantBuffers1);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI CSGetConstantBuffers1
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_CSGetConstantBuffers1, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::CSGetConstantBuffers1");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"StartSlot");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3D11BUFFER, L"ppConstantBuffers");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pFirstConstant");
AQU_D3D_NODE_COMMANDER(AQU_PNT_UINT, L"pNumConstants");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::CSGetConstantBuffers1);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI SwapDeviceContextState
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_SwapDeviceContextState, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::SwapDeviceContextState");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3DDEVICECONTEXTSTATE, L"pState");
AQU_D3D_NODE_COMMANDER(AQU_PPNT_ID3DDEVICECONTEXTSTATE, L"ppPreviousState");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::SwapDeviceContextState);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI ClearView
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_ClearView, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::ClearView");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11VIEW, L"pView");
AQU_D3D_NODE_COMMANDER(AQU_PNT_FLOAT, L"Color");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_RECT, L"pRect");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumRects");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::ClearView);
AQU_D3D_NODE_FOOTER___;

/**
* void WINAPI DiscardView1
***/
AQU_D3D_NODE_HEADER___(NOD_ID3D11DeviceContext1_DiscardView1, 320, 100);
AQU_D3D_NODE_TITLE____(L"ID3D11DeviceContext1::DiscardView1");
AQU_D3D_NODE_COMMANDER(AQU_PNT_ID3D11VIEW, L"pResourceView");
AQU_D3D_NODE_COMMANDER(AQU_PNT_D3D11_RECT, L"pRects");
AQU_D3D_NODE_COMMANDER(AQU_UINT, L"NumRects");
AQU_D3D_NODE_METHOD___(DirectX_11_1, ITA_D3D11INTERFACES::ITA_D3D11Interfaces::ID3D11DeviceContext1, VMT_ID3D11DEVICECONTEXT1::DiscardView1);
AQU_D3D_NODE_FOOTER___;

#pragma endregion

#pragma region ID3D11DeviceContext1 node provider method

/**
* Node provider class.
***/
class NOD_ID3D11DeviceContext1
{
public:
	/**
	* Provides ID3D11DeviceContext1 node by index.
	***/
	NOD_Basic* Get_ID3D11DeviceContext1Node(UINT dwIndex, LONG nX, LONG nY)
	{
		if (dwIndex > (UINT)VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::DiscardView1) return nullptr;
		if (dwIndex <= (UINT)VMT_IUNKNOWN::Release) return Get_ID3D11DeviceContext1_Node((VMT_IUNKNOWN::VMT_IUnknown)dwIndex, nX, nY);
		return Get_ID3D11DeviceContext1_Node((VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1)dwIndex, nX, nY);
	}

	/**
	* Provides IUnknown node by enumeration.
	***/
	NOD_Basic* Get_ID3D11DeviceContext1_Node(VMT_IUNKNOWN::VMT_IUnknown eMethod, LONG nX, LONG nY)
	{
		switch (eMethod)
		{
		case VMT_IUNKNOWN::VMT_IUnknown::QueryInterface:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_QueryInterface(nX, nY);
			break;
		case VMT_IUNKNOWN::VMT_IUnknown::AddRef:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_AddRef(nX, nY);
			break;
		case VMT_IUNKNOWN::VMT_IUnknown::Release:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_Release(nX, nY);
			break;
		default:
			break;
		}

		return nullptr;
	}

	/**
	* Provides ID3D11DeviceContext node by enumeration.
	***/
	NOD_Basic* Get_ID3D11DeviceContext1_Node(VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext eMethod, LONG nX, LONG nY)
	{
		switch (eMethod)
		{
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::VSSetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_VSSetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::PSSetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_PSSetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::PSSetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_PSSetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::PSSetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_PSSetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::VSSetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_VSSetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DrawIndexed:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DrawIndexed(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::Draw:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_Draw(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::Map:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_Map(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::Unmap:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_Unmap(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::PSSetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_PSSetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::IASetInputLayout:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_IASetInputLayout(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::IASetVertexBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_IASetVertexBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::IASetIndexBuffer:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_IASetIndexBuffer(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DrawIndexedInstanced:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DrawIndexedInstanced(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DrawInstanced:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DrawInstanced(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GSSetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_GSSetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GSSetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_GSSetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::IASetPrimitiveTopology:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_IASetPrimitiveTopology(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::VSSetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_VSSetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::VSSetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_VSSetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::Begin:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_Begin(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::End:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_End(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GetData:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_GetData(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::SetPredication:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_SetPredication(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GSSetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_GSSetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GSSetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_GSSetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::OMSetRenderTargets:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_OMSetRenderTargets(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::OMSetRenderTargetsAndUnorderedAccessViews:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_OMSetRenderTargetsAndUnorderedAccessViews(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::OMSetBlendState:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_OMSetBlendState(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::OMSetDepthStencilState:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_OMSetDepthStencilState(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::SOSetTargets:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_SOSetTargets(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DrawAuto:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DrawAuto(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DrawIndexedInstancedIndirect:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DrawIndexedInstancedIndirect(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DrawInstancedIndirect:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DrawInstancedIndirect(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::Dispatch:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_Dispatch(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DispatchIndirect:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DispatchIndirect(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::RSSetState:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_RSSetState(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::RSSetViewports:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_RSSetViewports(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::RSSetScissorRects:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_RSSetScissorRects(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CopySubresourceRegion:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_CopySubresourceRegion(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CopyResource:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_CopyResource(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::UpdateSubresource:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_UpdateSubresource(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CopyStructureCount:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_CopyStructureCount(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::ClearRenderTargetView:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_ClearRenderTargetView(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::ClearUnorderedAccessViewUint:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_ClearUnorderedAccessViewUint(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::ClearUnorderedAccessViewFloat:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_ClearUnorderedAccessViewFloat(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::ClearDepthStencilView:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_ClearDepthStencilView(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GenerateMips:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_GenerateMips(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::SetResourceMinLOD:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_SetResourceMinLOD(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GetResourceMinLOD:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_GetResourceMinLOD(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::ResolveSubresource:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_ResolveSubresource(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::ExecuteCommandList:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_ExecuteCommandList(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::HSSetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_HSSetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::HSSetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_HSSetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::HSSetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_HSSetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::HSSetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_HSSetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DSSetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DSSetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DSSetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DSSetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DSSetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DSSetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DSSetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DSSetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSSetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_CSSetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSSetUnorderedAccessViews:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_CSSetUnorderedAccessViews(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSSetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_CSSetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSSetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_CSSetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSSetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_CSSetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::VSGetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_VSGetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::PSGetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_PSGetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::PSGetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_PSGetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::PSGetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_PSGetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::VSGetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_VSGetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::PSGetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_PSGetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::IAGetInputLayout:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_IAGetInputLayout(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::IAGetVertexBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_IAGetVertexBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::IAGetIndexBuffer:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_IAGetIndexBuffer(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GSGetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_GSGetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GSGetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_GSGetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::IAGetPrimitiveTopology:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_IAGetPrimitiveTopology(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::VSGetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_VSGetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::VSGetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_VSGetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GetPredication:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_GetPredication(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GSGetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_GSGetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GSGetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_GSGetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::OMGetRenderTargets:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_OMGetRenderTargets(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::OMGetRenderTargetsAndUnorderedAccessViews:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_OMGetRenderTargetsAndUnorderedAccessViews(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::OMGetBlendState:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_OMGetBlendState(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::OMGetDepthStencilState:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_OMGetDepthStencilState(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::SOGetTargets:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_SOGetTargets(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::RSGetState:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_RSGetState(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::RSGetViewports:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_RSGetViewports(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::RSGetScissorRects:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_RSGetScissorRects(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::HSGetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_HSGetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::HSGetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_HSGetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::HSGetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_HSGetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::HSGetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_HSGetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DSGetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DSGetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DSGetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DSGetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DSGetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DSGetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::DSGetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DSGetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSGetShaderResources:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_CSGetShaderResources(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSGetUnorderedAccessViews:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_CSGetUnorderedAccessViews(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSGetShader:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_CSGetShader(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSGetSamplers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_CSGetSamplers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::CSGetConstantBuffers:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_CSGetConstantBuffers(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::ClearState:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_ClearState(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::Flush:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_Flush(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GetType:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_GetType(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::GetContextFlags:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_GetContextFlags(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT::VMT_ID3D11DeviceContext::FinishCommandList:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_FinishCommandList(nX, nY);
			break;
		default:
			break;
		}

		return nullptr;
	}

	/**
	* Provides ID3D11DeviceContext1 node by enumeration.
	***/
	NOD_Basic* Get_ID3D11DeviceContext1_Node(VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1 eMethod, LONG nX, LONG nY)
	{
		switch (eMethod)
		{
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::CopySubresourceRegion1:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_CopySubresourceRegion1(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::UpdateSubresource1:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_UpdateSubresource1(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::DiscardResource:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DiscardResource(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::DiscardView:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DiscardView(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::VSSetConstantBuffers1:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_VSSetConstantBuffers1(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::HSSetConstantBuffers1:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_HSSetConstantBuffers1(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::DSSetConstantBuffers1:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DSSetConstantBuffers1(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::GSSetConstantBuffers1:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_GSSetConstantBuffers1(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::PSSetConstantBuffers1:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_PSSetConstantBuffers1(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::CSSetConstantBuffers1:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_CSSetConstantBuffers1(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::VSGetConstantBuffers1:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_VSGetConstantBuffers1(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::HSGetConstantBuffers1:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_HSGetConstantBuffers1(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::DSGetConstantBuffers1:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DSGetConstantBuffers1(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::GSGetConstantBuffers1:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_GSGetConstantBuffers1(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::PSGetConstantBuffers1:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_PSGetConstantBuffers1(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::CSGetConstantBuffers1:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_CSGetConstantBuffers1(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::SwapDeviceContextState:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_SwapDeviceContextState(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::ClearView:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_ClearView(nX, nY);
			break;
		case VMT_ID3D11DEVICECONTEXT1::VMT_ID3D11DeviceContext1::DiscardView1:
			return (NOD_Basic*)new NOD_ID3D11DeviceContext1_DiscardView1(nX, nY);
			break;
		default:
			break;
		}

		return nullptr;
	}

};
#pragma endregion

#endif
