
#ifndef CONFIG_DEFAULTS_H_INCLUDED
#define CONFIG_DEFAULTS_H_INCLUDED

#define DEFAULT_YAW_MULTIPLIER 25.0f
#define DEFAULT_PITCH_MULTIPLIER 25.0f

#define DEFAULT_POS_TRACKING_X_MULT 2.0f
#define DEFAULT_POS_TRACKING_Y_MULT 2.5f
#define DEFAULT_POS_TRACKING_Z_MULT 0.5f

#define DEFAULT_GUI_SIZE_1 0.6f
#define DEFAULT_GUI_SIZE_2 0.5f
#define DEFAULT_GUI_SIZE_3 0.9f
#define DEFAULT_GUI_SIZE_4 1.0f
#define DEFAULT_HUD_DISTANCE_1 0.5f
#define DEFAULT_HUD_DISTANCE_2 0.9f
#define DEFAULT_HUD_DISTANCE_3 0.3f
#define DEFAULT_HUD_DISTANCE_4 0.0f

#endif